
MQTT_BROKER_IP = "18.218.123.57"
MQTT_BROKER_PORT =  1883
USER_NAME = "dan"
USER_PSWD = "stella"
REMOTE_STATION_NAME = "BlueMOven"
MQTT_MESSAGE_TOPIC = "OvenTemp"
N0_FEEDS = 1
FEED_1_LATEST_MEASUREMENT = "latest-measurement.txt"